### ISSUE TITLE
Clipit only works when "about" screen is open

### ISSUE THREAD

**Issue by e2002e** [CristianHenzel/ClipIt#102]
Hey I'm using Kali linux 2018 with the LXDE desktop, it's quit buggy and the problem I couldn't handle is with the copy/paste features.
It simply doesn't work at all excepted when the "about" tab or the "preferences" tab is opened....
What can be done to debug this ?

**Comment by procyclinsur** [comment]
I am experiencing the same issue with the below configuration.

OS: Fedora 29
Clipit: 1.4.3

Is there a solution to this yet?

**Comment by e2002e** [comment]
Are you also using LXDE ? I think you could replace it by another desktop like Gnome, or Cinamon if you want the closest from LXDE
