### ISSUE TITLE
Lack of search doc

### ISSUE THREAD

**Issue by DGPickett** [CristianHenzel/ClipIt#105]
I am still looking for how to search history.

**Comment by scorpp** [comment]
You can right-click on tray icon - Manage History. There is search.

**Comment by DGPickett** [comment]
First I need a tray icon, right?


 

 

-----Original Message-----

**Comment by jrrtck** [comment]
There is default shortcut to invoke Manage History and access the search function - Ctrl+Alt+F
You can invoke the tray menu even when tray is not available using Ctrl+Alt+P

So what desktop environment do you use, that you don't have tray icon?
