### ISSUE TITLE
how to save some items as snippets in clipit

### ISSUE THREAD

**Issue by chiju** [CristianHenzel/ClipIt#124]
I cant find to same some copy items as snippets and save them permamently.

If there is an option, please let me know.

**Comment by arantius** [comment]
AIUI this exists, it's called "static items".  To use:

1. Copy something.
2. Open the "manage history" menu.
3. Select the item you copied.
4. Press "edit".
5. Check "static item".
6. Press "OK".

Now this item appears permanently in your clipit list.
