### ISSUE TITLE
Please tag a new release v1.4.5

### ISSUE THREAD

**Issue by AngryPhantom** [CristianHenzel/ClipIt#133]
Please tag a new release **v1.4.5**.

Clipit doesn't work in Void Linux simply because they [do not accept](https://github.com/void-linux/void-packages/issues/20402#issuecomment-604901803) non-release versions (the answer to my issue).

The thing is that you [fixed](https://github.com/CristianHenzel/ClipIt/pull/90/commits/45e46d03b3ff315b5b380004d85fb499b4c139db) that issue in 2018.

Thank you in advance! Cheers.

**Comment by afelinczak** [comment]
New tag was added by @CristianHenzel, closing.

**Comment by AngryPhantom** [comment]
Thank you!
