### ISSUE TITLE
gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed

### ISSUE THREAD

**Issue by ngmariusz** [CristianHenzel/ClipIt#137]
(clipit:8124): Gdk-CRITICAL **: 21:24:29.686: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed

ubuntu 20.04
clipit 1.4.5
GNOME Shell 3.36.1

**Comment by afelinczak** [comment]
it is known issue, and PR to fix is sitting here for good few months.
You can:
- compile from sources from this fork https://github.com/jemyzhang/ClipIt (author of patch)
- downgrade to 1.4.2, download deb from ubuntu 18.04 repo and pin it
- or install from my ppa https://launchpad.net/~afelinczak/+archive/ubuntu/ppa
 
I'm trying to find better way to fix the issue, but for now jemyzhang change should do the trick.

**Comment by afelinczak** [comment]
jemyzhang PR has been merged, closing.
