### ISSUE TITLE
Hotkey for history is not working in Ubuntu 20.04

### ISSUE THREAD

**Issue by arunnambissan** [CristianHenzel/ClipIt#140]

**Comment by douglasb99** [comment]
clipit doesn't work in ubuntu 20.04, can confirm

**Comment by skudi** [comment]
Long story: #118 #97
last working version was 1.4.2...

**Comment by afelinczak** [comment]
use 1.4.2 as mentioned and pin it in synaptic
or use my ppa
https://launchpad.net/~afelinczak/+archive/ubuntu/ppa

**Comment by leikoilja** [comment]
Confirm that doesn't work on Ubuntu 20.04.

@afelinczak, legend! Thanks for the fix, i have installed it from your ppa and it works great! I love ClipIt, so i couldn't bare loosing it :smile:

**Comment by afelinczak** [comment]
PR is merged, so closing.
On my PPA and upladed deb file I increased timeout to 200ms, otherwise have crashes as well on my old laptop (Ubuntu Mate 20.04).
If anyone have similar behavior, please let me know - will increase timeout on master branch as well.

**Comment by arunnambissan** [comment]
I tried installing it again from ubuntu store but it's still not working. From where I should download the deb file?

**Comment by thepisu** [comment]
> I tried installing it again from ubuntu store but it's still not working. From where I should download the deb file?

You can download deb file for version 1.4.5 from here:
https://github.com/CristianHenzel/ClipIt/releases

Just tested that works.

**Comment by afelinczak** [comment]
2 options:
I packaged 1.4.5 here:
https://github.com/CristianHenzel/ClipIt/releases/tag/v1.4.5

also there is my ppa - but it is intended for testing patches before merging to master:
https://launchpad.net/~afelinczak/+archive/ubuntu/ppa

**Comment by arunnambissan** [comment]
I have downloaded the deb file, but it's stuck on the loading screen.
![Screenshot from 2020-06-12 14-35-25](https://user-images.githubusercontent.com/12548805/84485794-1c7bee80-acba-11ea-81ed-a108ecb60b7b.png)

**Comment by afelinczak** [comment]
Have similar issues on Ubuntu Mate 20.04, sometimes installing deb just hangs.
Maybe try from command line 
`sudo gdebi clipit_1.4.5_amd64.deb` - not sure sitting on Windows now, I will try to verify again tomorrow.

**Comment by arunnambissan** [comment]
Thanks, it worked using gdebi
