### ISSUE TITLE
There is no 'Use right-click menu' in your .deb package

### ISSUE THREAD

**Issue by AngryPhantom** [CristianHenzel/ClipIt#142]
Hello,

Strange, but if I install your clipit_1.4.5_amd64.deb package there is no 'Use right-click menu' option in the [preferences](http://0x0.st/iWyg.png).
But if I compile it myself on Debian Stable (Buster 64bit) the option is [present](http://0x0.st/iWyY.png).

It's not a problem for me to recompile ClipIt, but probably you should fix & update the .deb package for others since this option is pretty handy. At least, I enable it firsthand :)

Thank you!

**Comment by afelinczak** [comment]
Thanks for your feedback.
I was building packages using debian scripts obtained from Ubuntu source packages and by default it is compiling with --enable-appindicator.
With appindicator right-click menu is disabled.
I attached new packages compiled only with --with-gtk3, so option will be available now.

It would be great if someone can test it on Ubuntu 20.04.

Cheers,
Arek

**Comment by AngryPhantom** [comment]
>--with-gtk3

Oh, I should have mentioned that. Yes, compiling with this only option is what enables this feature/checkbox. Btw, at first I guessed that gtk3 is the default setting, so was pretty surprised when it didn't compile.
Anyway, thank you for the feedback and package reuploading. Cheers!
