### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by CallumBaston** [CristianHenzel/ClipIt#146]
On the list of install requirements you are missing the dependency that is needed for install named "intltoolize". The script fails with out it.

**Comment by afelinczak** [comment]
Yes, I noticed that as well.
I will update Readme adding dependency based on debian build scripts.
Will also update that on meson PR, I would really like to depracate autotools. With that we can drop intltoolize as well and move to gettext.

**Comment by afelinczak** [comment]
Readme file updated
