### ISSUE TITLE
Clipit stoped working after update to Minto 20

### ISSUE THREAD

**Issue by jkatnik** [CristianHenzel/ClipIt#148]
Hi,

I use ClipIt for a while and I love it. Thanks.
Recently I updated Mint 19.3 to 20.
If I click on ClipIt icon it displays correctly, however when I try to access it via keyboard shortcut it doesn't work. Than if I try to open preferences from sys tray an empty panel pops up and it doesn't disappear until I kill the process.

![image](https://user-images.githubusercontent.com/7869474/88178630-fa677b80-cc2a-11ea-87ed-8f5674699820.png)

I use latest (1.4.5) version.
I tried to reinstall ClipIt but it didn't helped.

Did someone had the same issue and knows how to fix?

Thanks in advance!

**Comment by afelinczak** [comment]
Patched version is available here on github:
https://github.com/CristianHenzel/ClipIt/releases/tag/v1.4.5

**Comment by jkatnik** [comment]
wow that was fast! Patched version works like a charm. Thanks a lot!

**Comment by Tert0** [comment]
Im the AUR Maintainer.
The Arch Package is using the Version 1.4.5 but I have the same Issues.
Tert0

**Comment by afelinczak** [comment]
Hello @Tert0,
Can you compile sources from master branch (not 1.4.5) and let me know if it is broken ?
I don't have Arch/Manjaro to verify.

**Comment by Tert0** [comment]
I will try it later and tell the Result here

**Comment by rhodium88** [comment]
I don't know if @Tert0 has had a chance to try this yet, but I was having the same problem on Arch. Compiling from the master branch solved the problem for me.
