### ISSUE TITLE
[bug?] Ctrl+alt+h doesn't bring up history view on ubuntu 20.04

### ISSUE THREAD

**Issue by arooni** [CristianHenzel/ClipIt#150]
clipit is already the newest version (1.4.4+git20190202-1).

![image](https://user-images.githubusercontent.com/556667/91480349-724b4600-e868-11ea-8e4f-6947e6e8377c.png)

Not sure what to do?  Many thanks!

When I hit ctrl+alt+h nothing happens.

**Comment by afelinczak** [comment]
Install clipit 1.4.5 from github (deb file from releases tab) or version from ppa.
Issue is fixed there, but it wasn't pushed upstream sadly.

**Comment by i3130002** [comment]
Nope, the `clipit_1.4.5_amd64.deb` won't install `not supported` and the `clipit_1.4.5_amd64_indicator.deb` won't open.
