### ISSUE TITLE
History indexes don't correspond to number pressed for automatic paste

### ISSUE THREAD

**Issue by sdragnev** [CristianHenzel/ClipIt#155]
With "automatically paste selected item" turned on, pressing a corresponding number should paste the item with that index in the history.
The issue is that the history show in the popup starts at 1 where the actual list starts at 0.

For example, if the history is as such:

1. One
2. Two

Pressing the history hotkey followed by 1 would actually paste "Two".
Pressing 0 would paste One.

**Comment by afelinczak** [comment]
This issue is now fixed thanks to @jgidi PR.
Will update ppa builds soon.

**Comment by timothyjensen** [comment]
Thank you for addressing this!
