### ISSUE TITLE
Ubuntu repo states Clipit licence is "proprietary"

### ISSUE THREAD

**Issue by Jakethethird** [CristianHenzel/ClipIt#157]
This must be an error...GPL-3.0 License isn't it?

Jake.

![20201019_screenshot_002](https://user-images.githubusercontent.com/28954472/96466046-38b80b00-1219-11eb-9cd1-bdba784039c8.png)

**Comment by CristianHenzel** [comment]
Yeah, license is available in the repo: https://github.com/CristianHenzel/ClipIt/blob/master/COPYING

As you can see, it has not been changed since 2010. Not sure why they tagged it that way.
