### ISSUE TITLE
what to write for using the escape key as hotkey

### ISSUE THREAD

**Issue by sidmint** [CristianHenzel/ClipIt#163]
what to write for using the escape key as hotkey, in combination or alone.

i tried Esc, esc, Escape, escape but no success.

**Comment by peroxy** [comment]
Can you try ESC or GRAVE_ESC or grave_esc or something similar?

**Comment by sidmint** [comment]
> Can you try ESC or GRAVE_ESC or grave_esc or something similar?

no luck

**Comment by sidmint** [comment]
sorry for the trouble, the code is simply Escape but i don't know why it didn't work before. Maybe it wasn't working due to related key binding I might have removed just moment before testing this.
