### ISSUE TITLE
<Ctrl>` shortcut doesn't work

### ISSUE THREAD

**Issue by Loreno10** [CristianHenzel/ClipIt#169]
I tried setting up \<Ctrl\>\` as a shortcut for history view. It just doesn't work.

**Comment by MandySimbuka** [comment]
@Loreno10 You can't only use `<Ctrl>` since it is a modifier, you can however use something like `<Ctrl>H`

**Comment by OhMyMndy** [comment]
@Loreno10 You can't only use `<Ctrl>` since it is a modifier, you can however use something like `<Ctrl>H`

**Comment by Loreno10** [comment]
I’m not using only CTRL. There is CTRL and a back tick.

**Comment by OhMyMndy** [comment]
I tried to use `<Ctrl>``, ran `clipit` from the command line and it core dumped when pressing that key combination...

**Comment by CristianHenzel** [comment]
Duplicate of #70 70
