### ISSUE TITLE
keyboard shortcut not working Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by lskal** [CristianHenzel/ClipIt#194]
hey guys, I've downloaded the program using `sudo apt install clipit` on Ubuntu 20.04.2 LTS and the keyboard shortcuts are not working. I've tried to uninstall and install and nothing changes. 
I also noticed that the icon of clip it duplicates itself in the top dashboard and i get this ... thing too for some reason.
I love this tool, but is not working anymore for me so far.
Thanks for your time guys and for this super useful tool,
Max

PS: i gonna leave a screenshot of the dashboard as attachment 
![Schermata da 2021-08-27 12-34-15](https://user-images.githubusercontent.com/46959649/131114353-9d4f5897-e8e8-4ea4-a95d-eea7622b5a70.png)

**Comment by dcomsa** [comment]
I have the same issue on `Ubuntu 20.04.3 LTS`

If I run it from command line, I see the following in the output:
```
(clipit:2645965): Gdk-CRITICAL **: 09:46:02.241: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
```

Could be related to issue https://github.com/CristianHenzel/ClipIt/issues/137?

**Comment by lskal** [comment]
@dcomsa what is the comand i need to execute? I've tried to install the solution `install from my ppa`, but it doesn't seem working

**Comment by lskal** [comment]
so, i've run in the terminal `clipit` and i got this result:
![Schermata da 2021-09-09 09-32-03](https://user-images.githubusercontent.com/46959649/132642735-baeaa42d-d86a-4d68-8fab-d9e1b26b899b.png)

**Comment by lskal** [comment]
also if I click on `information` or `manage history` in the app settings I get this black window that i cant close

**Comment by r4space** [comment]
Same issues as above reports - anyone managed to find more on the problem/a workaround?
