### ISSUE TITLE
Clipit wakes up the CPU 60 times a second

### ISSUE THREAD

**Issue by hrj** [CristianHenzel/ClipIt#23]
On my Ubuntu 13.04 system with Clipit 1.4.1, powertop shows Clipit wakes up the CPU 60 times a second.

Surely that's not required and wastes energy and battery.

Can this be reduced?

**Comment by rejdi** [comment]
I fixed the issue. It's available in my repo https://github.com/rejdi/ClipIt

**Comment by COLABORATI** [comment]
Has this been fixed in the release that comes with Ubuntu 16.04 LTS?

**Comment by rejdi** [comment]
I don't know. I'm using Archlinux and building the app myself. Please ask maintainer for Ubuntu. I know that this guy https://github.com/mbarczak/ClipIt/commits/master used my patch and now I see, that this repo seems to be most active, so maybe I'll do rebase / pull request here also.
