### ISSUE TITLE
Clipit actions info request

### ISSUE THREAD

**Issue by pgarcpri** [CristianHenzel/ClipIt#49]
Could anyone please explain how to use the actions feature of clipit?
I've tried to use bash scripting but nothing happens when action is selected.
I've also tried to set just '%s' in the command to check if it returns the same value than selected bu nothing happens. I'm missing something...

Is this feature really working?

Thanks for the help.
Pablo

**Comment by CristianHenzel** [comment]
You need to execute a whole command in the action, not just the string from the clipboard. That will not work, unless the string contains an actual executable command.
You could for example have an action containing:
*echo "%s" > /tmp/somefile.txt*
to write the string contained in the clipboard item to somefile.txt in the /tmp/ directory.
