### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Sadi58** [CristianHenzel/ClipIt#54]
I tried compiling ClipIt under Ubuntu 16.10 as specified in README here but I've got the following error at the end of the second (./configure) step:

```
checking for GTK... no
configure: error: Package requirements (gtk+-2.0 >= 2.10) were not met:

No package 'gtk+-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GTK_CFLAGS
and GTK_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by andyforceno** [comment]
I'm getting a similar error during `./configure` (I have Ubuntu 14.04.5)

>./configure: line 7916: syntax error near unexpected token 2.10.0,'
./configure: line 7916: AM_PATH_GTK_2_0(2.10.0, , as_fn_error $? "Requirement not met: gtk >=     2.10.0" "$LINENO" 5)'`

According to `dpkg -l libgtk* | grep -e '^i' | grep -e 'libgtk-*[0-9]'` I have GTK  2.24.23-0ubuntu1.4 and 3.14.15-0ubuntu1-14.04-ricotz1

What needs to be changed, and where, to get this configured and compiled?

**Comment by CristianHenzel** [comment]
Hello,

on Ubuntu please try installing "libgtk2.0-dev".
