### ISSUE TITLE
question - meaning of Offline mode?

### ISSUE THREAD

**Issue by weaktyper** [CristianHenzel/ClipIt#56]
Hi, I have a general question about the meaning of offline mode for clipit...
What does it mean in Clipit?

**Comment by itsSaad** [comment]
wondering the same thing. :+1:

**Comment by CristianHenzel** [comment]
Hello,


ClipIt polls the content of the clipboard every 500 milliseconds.  If the text from the clipboard does not match any entry in ClipIt's history, it adds the item as a new item.
When offline mode is enabled, the polling function exits immediately, without checking for new items or adding new items.

**Comment by mtomilov** [comment]
Maybe it can be renamed to something else? As it is, it's quite misleading.
My suggestion: Disabled
