### ISSUE TITLE
Parcellite "Remove History" Only Removes One Item at a Time

### ISSUE THREAD

**Issue by gtsfer** [CristianHenzel/ClipIt#64]
Parcellite 1.1.9-1 (installed from repository)

OS: Distro: Linux Mint 18.1 KDE (Serena)
     Kernel: 4.4.0-53-generic x86_64 (64 bit gcc: 5.4.0)
     Desktop: KDE Plasma 5.8.5 (Qt 5.6.1)

"Clear history" from parcellite in the system tray removes one item at a time. It does not perform a clear of all history.

Same with Linux Mint 18 KDE as well. (currently currently running LM 18.1 KDE)

**Comment by CristianHenzel** [comment]
Hello,

this isn't the project page for Parcellite, but rather ClipIt, a separate project, that was forked from Parcellite.
If you're using Parcellite, please address this issue to their issue tracker.
