### ISSUE TITLE
"About" menu item shows URL to a zero-informative website

### ISSUE THREAD

**Issue by COLABORATI** [CristianHenzel/ClipIt#69]
The "About" dialog contains a link to http://clipit.rspwn.com/ - which is a zero informtative website with some user-unfriendly "nothing to see here" message and bad certificates - please update this to link to at least some basic information about the program or this github repo.

**Comment by CristianHenzel** [comment]
You might have an older version, since this URL has been changed in the about menu quite some time ago.
