### ISSUE TITLE
Back tick "`" do not work with history hotkey

### ISSUE THREAD

**Issue by sgnsajgon** [CristianHenzel/ClipIt#70]
I use Ditto Clipboard Manager on Windows and I'm used to default "Ctrl-`" history hotkey (control + back stick). It would be great to be able to use the same hotkey for ClipIt on Ubuntu. Currently hotkey with back stick do not work.

**Comment by jirikrepl** [comment]
Yes same thoughts here! I use Ditto on also Windows with CTRL+`

**Comment by facetoe** [comment]
This seems to be a limitation in the library used for binding keys. It appears that any punctuation character causes `gdk_keyval_from_name` to return 0 in https://github.com/CristianHenzel/ClipIt/blob/master/src/eggaccelerators.c#L316. Not sure how this could be resolved.

**Comment by Epskampie** [comment]
Good news! You can actually use backtick, but you have to specify the hotkey like this:

`<Ctrl>grave`

I looked for a long time for this. :-)

**Comment by facetoe** [comment]
Excellent!

**Comment by thebunnyrules** [comment]
Thanks so much, I tried <Ctrl>Grave it didn't occur to me to try <Ctrl>grave.

**Comment by CGjupoulton** [comment]
How did you find this information? What if we want a semicolon or other punctuation character, how do we find out?

**Comment by peroxy** [comment]
> Good news! You can actually use backtick, but you have to specify the hotkey like this:
> 
> `<Ctrl>grave`
> 
> I looked for a long time for this. :-)

What a champ, thanks so much :+1:

**Comment by sidmint** [comment]
thanks @Epskampie, was looking for it but using Shift+Tab now anyway.

But I still could not figure out how to use the escape key, anyone's help would be appreciated.

**Comment by sidmint** [comment]
this issue can be closed now.
