### ISSUE TITLE
Errors generated while running automake

### ISSUE THREAD

**Issue by eldruin** [CristianHenzel/ClipIt#74]
There are 3 errors being generated. See the log:

> ./autogen.sh             
autopoint...
Creating /aclocal.m4 ...
Running autopoint...  Ignore non-fatal messages.
Making aclocal.m4 writable ...
intltoolize...
aclocal...
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:22: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
configure.in:82: warning: macro 'AM_PATH_GTK_2_0' not found in library
configure.in:83: warning: macro 'AM_PATH_GLIB_2_0' not found in library
autoheader...
automake...
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:6: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.in:6: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
configure.in:28: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.in:28: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.in:28: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
configure.in:28: installing './compile'
configure.in:28: installing './config.guess'
configure.in:28: installing './config.sub'
configure.in:6: installing './install-sh'
configure.in:6: installing './missing'
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
src/Makefile.am:4: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
src/Makefile.am: installing './depcomp'
autoconf...
configure.in:22: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.in:82: error: possibly undefined macro: AM_PATH_GTK_2_0
configure.in:83: error: possibly undefined macro: AM_PATH_GLIB_2_0
now run configure

**Comment by CristianHenzel** [comment]
If you install all of the required libraries before running automake, you should not get any errors.
