### ISSUE TITLE
1.4.3 tag

### ISSUE THREAD

**Issue by AMDmi3** [CristianHenzel/ClipIt#82]
1.4.3 version is listed in the changelog, but there are neither tag nor sourceforge release. Was 1.4.3 actually released or is this a development version? Cause it's already used by packages https://repology.org/metapackage/clipit/versions

**Comment by jrmarino** [comment]
It looks like issue #68 deals with the same topic.
It also looks like CristianHenzel isn't responding to any "recent" (e.g. last few months) issues.

**Comment by CristianHenzel** [comment]
1.4.3 was used for development, but since it has been a long time since the last release, I just bumped to 1.4.4.
