### ISSUE TITLE
cppcheck error: Uninitialized variable: count

### ISSUE THREAD

**Issue by onlyjob** [CristianHenzel/ClipIt#91]
`cppcheck` found the following error:

~~~~
[main.c:576]: (error) Uninitialized variable: count
~~~~

https://github.com/CristianHenzel/ClipIt/blob/master/src/main.c#L576

**Comment by CristianHenzel** [comment]
Fixed by 8c5c3e67c0e08893bb432834d36efdb9c6963a25

**Comment by onlyjob** [comment]
Thanks. :)
