### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by onlyjob** [CristianHenzel/ClipIt#98]
Clipit just got killed by OOM killer on machine with 40+ GiB of (free) RAM.

Apparently sometimes it leaks memory rapidly but I'm not sure how to reproduce.
It seems to happen randomly on Debian GNU/Linux "testing" in Cinnamon Desktop Environment, _amd64_.

**Comment by jrrtck** [comment]
I can reproduce memory leak reliably, when opening Manage history page. Every time this window appears, entire history list is leaked. After applying above patch, clipit's memory usage is stable. I've tested it for period of several months by means of common daily usage.

**Comment by afelinczak** [comment]
Patch merged, closing
